# Generated by Django 5.1.3 on 2024-11-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=15, verbose_name='Estado de la Cita')),
                ('comentarios_cliente', models.TextField(blank=True, null=True, verbose_name='Comentarios del Cliente')),
                ('comentarios_emprendedora', models.TextField(blank=True, null=True, verbose_name='Comentarios de la Emprendedora')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to='usuarios.usuario', verbose_name='Cliente')),
                ('emprendedora', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Emprendedora'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_emprendedora', to='usuarios.usuario', verbose_name='Emprendedora')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_servicio', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
