# Generated by Django 5.1.3 on 2024-11-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')], help_text='Calificación de 1 a 5 estrellas', verbose_name='Calificación')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_opinion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Opinión')),
                ('estado', models.BooleanField(default=True, verbose_name='Visible')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='usuarios.usuario', verbose_name='Cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name_plural': 'Opiniones',
                'ordering': ['-fecha_opinion'],
            },
        ),
    ]
