# Generated by Django 5.1.3 on 2024-11-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Servicio')),
                ('duracion', models.PositiveIntegerField(help_text='Duración aproximada en minutos.', verbose_name='Duración (minutos)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('emprendedora', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Emprendedora'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='usuarios.usuario', verbose_name='Emprendedora')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre_servicio'],
            },
        ),
    ]
